### ISSUE TITLE
Exult crashes

### ISSUE THREAD

**Issue by DrewDunnam** [exult/exult#305]
Running exult version 1.8, after destroying the tetrahedron generator, the game crashes back to main menu or desktop, during combat…every time. Doesn’t happen until after the tetrahedron. Before, combat is fine, after combat = crash.

**Comment by DominusExult** [comment]
Can you try the recent snapshot? This sounds like an issue we already fixed.

**Comment by DrewDunnam** [comment]
Sad panda. I don’t know what u mean by snapshot. Reading through the website snapshot is used often…alas it’s beyond my comprehension.

**Comment by DominusExult** [comment]
http://exult.info/download.php

http://exult.info/faq.php#whatis_snapshot

**Comment by corb365** [comment]
I have the same crashing problem, and have to admit that the faq and documentation don't help me at all (yes, I'm basically computer-illiterate). I downloaded the latest snapshot, opened it, and am looking at a folder that has a link at the top left, Exult in the middle top, and a "drag here" folder in the top right, with documentation along the bottom. When I try to drag the Exult app into the folder, it tells me that I now have two copies of the application. Am I supposed to overwrite the existing Exult? If so, will that destroy all the progress I've made in the game? Am I missing something entirely? Thanks.

**Comment by corb365** [comment]
Alas, it still won't open. Also tried re-downloading Exult 1.8, then the latest snapshot, and it just tells me "Exult quit unexpectedly" every time. Any suggestions would be great; thanks.

**Comment by DominusExult** [comment]
Dang!
Please try to do this:
Right click the exult.app and select "show contents".
Then the Finder will show the folder "contents". Doubleclick that, then doubleclick "macos" and finally the "exult" binary.
Two things should happen:
A terminal window will open and Exult will start (and crash if it does that for you on starting).

After it crashes, please copy the content of the terminal window (you can just mark it with the mouse and then hit command+c) and paste into a reply here.

**Comment by corb365** [comment]
Yup, everything happened as you predicted. Here's what the terminal window says (with my name redacted); hope it helps:

Last login: Sat Mar 18 23:10:43 on console
xxx MacBook-Air:~  xxx/Applications/Exult.app/Contents/MacOS/exult ; exit;
Exult version 1.9.0git
Built at: Mar 20 2023 22:24:34
Compile-time options: USE_FMOPL_MIDI, USE_MT32EMU_MIDI, USE_EXULTSTUDIO, HAVE_ZIP_SUPPORT
Compiler: GCC Apple LLVM 14.0.0 (clang-1400.0.29.202)

Platform: Mac OS X
Assertion failed: (s[nn] == '<'), function read_config_string, file Configuration.cc, line 127.
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...25 completed.

[Process completed]

**Comment by DominusExult** [comment]
Oh wow, not much in that.
I suspect your exult.cfg has somehow been corrupted.
Please open Terminal and enter (or copy/paste and enter)
`mv ~/Library/Preferences/exult.cfg ~/Library/Preferences/exult.cfg.OLD`
This renames your exult.cfg to exult.cfg.OLD and when you start Exult again it will generate a new exult.cfg. And then hopefully work!

Could you also tell me your macOS version?

**Comment by corb365** [comment]
It worked; thanks!

I'm running Sierra 10.12.6, which isn't super-new, I admit.

Really appreciate the help.

**Comment by DominusExult** [comment]
As long as it works :)
And we do have a strong backward compatibility. In theory :) (hence I asked for your macOS version)
